title: Another Blog

url: "https://rustlang.kr" 

baseurl: ""

timezone: Asia/Seoul

description: >
  One or more sentences introducing this blog.
  
email: your_email@example.com

author: DebugJO

avatar: "https://avatars.githubusercontent.com/u/18445776?v=4"

profile: Software Engineer / Developer

twitter_username: DebugJO

github_username:  DebugJO

profile_links:
  Email: "mailto:me@msjo.kr"
  GitHub: "https://github.com/DebugJO"

excerpt_separator: <!--more-->

header:
  links:
    About: /about/
    Category: /category/

permalink: /archivers/:title

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
