title: RustLang.kr

url: "https://rustlang.kr" 

baseurl: ""

timezone: Asia/Seoul

description: >
  Rust Language.
  
email: me@msjo.kr

author: MSJO

avatar: "https://msjo.kr/images/logo-dev.png"

profile: Software Engineer / Developer

#twitter_username: DebugJO
#github_username:  DebugJO

profile_links:
  Email: "mailto:me@msjo.kr"
  GitHub: "https://github.com/DebugJO"

excerpt_separator: <!--more-->

header:
  links:
    About: /about/
    Category: /category/

permalink: /:year/:month/:day/:title/

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
